config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  resources :secret_codes, only: [:index] do
    collection do
      post :generate
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    # can :read, SecretCode, :all
    if user.admin?
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/secret_code.rb
class SecretCode < ApplicationRecord
  has_one :user

  scope :not_used, -> { where.not(id: User.pluck(:secret_code_id)) }

  SIZE_OPTIONS = [1, 10, 20, 50, 100]
  DEFAULT_SIZE_OPTION = 10

  def self.generate(size: DEFAULT_SIZE_OPTION)
    while !size.zero?
      duplicate = 0
      size.times do
        unless SecretCode.create(code: self.get_random_code)
          duplicate += 1
        end
      end
      size = duplicate
    end
    true
  end

  private

    def self.get_random_code
      SecureRandom.hex(3)
    end
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :validatable and
  # :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :validatable

  belongs_to :secret_code

  def admin?
    self.has_role? :admin
  end

end

app/models/users_role.rb
class UsersRole < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def page
    params[:page].presence || 1
  end

  def per_page
    params[:per_page].presence || 10
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController
  authorize_resource through: :current_user

  def index
    @secret_codes = SecretCode.all.page(page).per(per_page).includes(:user)
  end

  def generate
    if SecretCode.generate(size: params[:size].to_i)
      redirect_to secret_codes_path, notice: 'Codes created successfully'
    else
      redirect_to secret_codes_path, alert: 'Something went wrong!'
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation,
        :secret_code_id)
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretCode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class='container'>
        <div class="row">
          <div class="col-md-12">

            <div class="pull-left">
              <div class="logo">
                <h2>Admin</h2>
              </div>
            </div>

            <div class="pull-right">
              <% if user_signed_in? %>
                <div class="btn-group" style="margin-top: 23px; margin-right: 10px;">
                  <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= current_user.email %>&nbsp;&nbsp;&nbsp;<span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu right-align">
                    <% if can? :manage, SecretCode %>
                      <li><%= link_to 'Secret Codes', secret_codes_path %></li>
                    <% end %>
                    <li><%= link_to 'Sign Out', destroy_user_session_path, method: 'DELETE' %></li>
                  </ul>
                </div>
              <% else %>
                <div class="btn-group" style="margin-top: 23px; margin-right: 10px;">
                  <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Sign In&nbsp;&nbsp;&nbsp;<span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu right-align">
                    <li><%= link_to 'Sign In', new_user_session_path %></li>
                  </ul>
                </div>
              <% end %>
            </div>

          </div>
        </div>
      </div>
    </header>
    <div class="container">
      <% if notice.present? %>
        <div class="alert alert-info alert-dismissible"" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      <% end %>

      <% if alert.present? %>
        <div class="alert alert-danger alert-dismissible"" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/secret_codes/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h3 class="center">Secret Codes</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">

      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <%= form_tag generate_secret_codes_path, class: 'form-inline' do %>
              <div class="form-group form-group-sm">
                <%= label_tag "size" ,"Size"  %>
                <%= select_tag "size", options_for_select(SecretCode::SIZE_OPTIONS, params[:size] || SecretCode::DEFAULT_SIZE_OPTION), class: 'form-control' %>
              </div>
              <%= submit_tag "Generate", class: 'btn btn-sm btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="table-responsive">
        <table class="table table-bordered table-condensed">
          <tr>
            <th>Id</th>
            <th>Code</th>
            <th>Email</th>
          </tr>

          <% @secret_codes.each do |secret_code| %>
            <tr>
              <td><%= secret_code.id %></td>
              <td><%= secret_code.code %></td>
              <td><%= secret_code.user.try(:email) %></td>
            </tr>
          <% end %>
        </table>
      </div>

      <div class="panel-footer" style="padding: 0px">
        <%= paginate @secret_codes %>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>